const mongoose = require("mongoose");
const Schema = mongoose.Schema;

let deviceSchema = new Schema({
    image: { type: String, require: true },
    Brand: { type: String, require: true },
    DeviceName: { type: String, require: true },
    announced: { type: String, require: true },
    battery_c: { type: String, require: true },
    bluetooth: { type: String, require: true },
    card_slot: { type: String, require: false },
    charging: { type: String, require: false },
    chipset: { type: String, require: true },
    colors: { type: String, require: false },
    cpu: { type: String, require: true },
    dimensions: { type: String, require: true },
    features: { type: String, require: false },
    features_c: { type: String, require: false },
    gps: { type: String, require: true },
    gpu: { type: String, require: true },
    internal: { type: String, require: true },
    loudspeaker_: { type: String, require: false },
    models: { type: String, require: false },
    network_c: { type: String, require: false },
    nfc: { type: String, require: true },
    os: { type: String, require: true },
    price: { type: String, require: true },
    protection: { type: String, require: false },
    radio: { type: String, require: false },
    resolution: { type: String, require: true },
    sar: { type: String, require: false },
    sensors: { type: String, require: false },
    sim: { type: String, require: false },
    single: { type: String, require: false },
    size: { type: String, require: true },
    sound_c: { type: String, require: false },
    speed: { type: String, require: true },
    status: { type: String, require: false },
    tecnology: { type: String, require: false },
    technology: { type: String, require: false },
    triple: { type: String, require: false },
    usb: { type: String, require: false },
    video: { type: String, require: false },
    weight: { type: String, require: false },
    wlan: { type: String, require: false },
    _2g_bands: { type: String, require: false },
    _3_5mm_jack_: { type: String, require: false },
    _3g_bands: { type: String, require: false },
    _4g_bands: { type: String, require: false },
    type: { type: String, require: false },
    display_c: { type: String, require: false },
    body_c: { type: String, require: false },
    build: { type: String, require: false },
    dual_: { type: String, require: false },
    performance: { type: String, require: false },
    memory_c: { type: String, require: false },
    _5g: { type: String, require: false },
    infrared_port: { type: String, require: false },
    quad: { type: String, require: false },
    camera: { type: String, require: false }
})

module.exports = deviceSchema